language: python
sudo: false
python:
  - "2.7"

before_install:
  - pip install codecov

install:
  - travis_retry pip install .
  - pip install -r requirements.txt

script:
  - make test

after_success:
  - codecov
