language: python
sudo: false
python:
  - "2.7"
  - "3.5"

before_install:
  - pip install codecov

install:
  - travis_retry pip install .
  - pip install -r requirements.txt

script:
  - nosetests

after_success:
  - codecov
